apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-taxi
    openshift.gitops/environment: app-taxi-dev
  name: app-taxi-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: app-taxi-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/dev/
    repoURL: https://github.com/ciiay/simple-env-setup.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
